plugins:
  - rubocop-rails
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.3
  SuggestExtensions: false

  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "bin/**/*"
    - "node_modules/**/*"
    - "tmp/**/*"

Rails:
  Enabled: true

RSpec:
  Enabled: true
